name: Build Android App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-18.04
   steps:
    - uses: sparkfabrik/android-build-action@v1.0.0
      with:
        project-path: protectid__armeabi-v7a
        output-path: my-app.apk
        browserstack-upload: false
